feat: in scene scenario layer editor
scenario-labs/Scenario-Unity pull request #177
Opened 2024-05-25 15:32 UTC by mrbusysky

I have updated the code to now allow for the removal of background and so on to happen in the scene window. It updates the sprite where it is.

2024-05-29 13:20 UTC, TheLLspectre requested changes

2024-05-29 13:20 UTC, TheLLspectre commented on package/Editor/SceneTools/SceneContextMenuActions/SceneContextMenuActions.cs
> +        private static void RemoveBackground()
Could you comment this method ?

2024-05-29 13:20 UTC, TheLLspectre commented on package/Editor/SceneTools/SceneContextMenuActions/SceneContextMenuActions.cs
> +                uncompressedTexture.SetPixels(texture2D.GetPixels());
What about if the sprite selected is not from Scenario ? Default sprite ?

2024-05-29 13:20 UTC, TheLLspectre commented on package/Editor/SceneTools/SceneContextMenuActions/SceneContextMenuActions.cs
> +        private static void SetAsBackground()
Could you comment this method ?

2024-05-29 13:20 UTC, TheLLspectre commented on package/Editor/Plugins/CommonUtils.cs
> +        public static void ReplaceSprite(SpriteRenderer spriteRenderer, Texture2D newTexture)
Could you comment this method ?

2024-05-29 14:55 UTC, mrbusysky commented on package/Editor/SceneTools/SceneContextMenuActions/SceneContextMenuActions.cs
> +        private static void OnSceneGUI(SceneView sceneView)
The private static you mean?

2024-06-07 08:05 UTC, TheLLspectre requested changes

2024-06-07 08:05 UTC, TheLLspectre commented on package/Editor/SceneTools/SceneContextMenuActions/SceneContextMenuActions.cs
> +                uncompressedTexture.SetPixels(texture2D.GetPixels());
![image](https://github.com/scenario-labs/Scenario-Unity/assets/30622829/a907d2da-4d07-4c50-8cf3-02b2c217033c)

Still have this error on default sprite from Unity

2024-06-10 20:29 UTC, mrbusysky commented
Should now be sorted.

2024-07-12 17:24 UTC, closed without merging